;this is a great way to demonstrate the power of variables

#WINDOW_FLAG = #PB_Window_SystemMenu | #PB_Window_ScreenCentered
#GADGET_FLAG = #PB_Text_Center | #PB_Text_Border

DigitOne.s = Str ( Random ( 9 ) )
DigitTwo.s = Str ( Random ( 9 ) )
DigitThree.s = Str ( Random ( 9 ) )
DigitFour.s = Str ( Random ( 9 ) )

MessageDisplay.s = "Password generated by the Computer: "

Concatenated.s = DigitOne + DigitTwo + DigitThree + DigitFour

If OpenWindow(0, 0, 0, 720, 100, "Variables At Work", #WINDOW_FLAG)
  LoadFont(0, "Verdana", 18)
  SetGadgetFont(#PB_Default, FontID(0))  
  TextGadget(5, 10, 30, 700, 38, MessageDisplay + Concatenated, #GADGET_FLAG)
  Repeat : Until WaitWindowEvent() = #PB_Event_CloseWindow
EndIf

